networks:
    bands:
        external: false

services:
    bands:
        container_name: bands
        build:
            context: .
        restart: always
        networks:
            - bands
        volumes:
            - .:/repo
