---
networks:
  bands:
    external: false

services:
  bands:
    #build:
    #  context: .
    image: ghcr.io/gottaeat/bands:latest
    container_name: bands
    restart: unless-stopped
    networks:
      - bands
    volumes:
      - ./data:/data
